FROM hyperledger/besu:latest

USER root

RUN --mount=type=cache,target=/var/cache/apt --mount=type=cache,target=/var/lib/apt \
    apt-get update && apt-get install -y jq curl && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/besu/plugins

COPY build/libs/besu-plugin-permissioning.jar /opt/besu/plugins/besu-plugin-permissioning.jar

USER besu
